import { auth } from "@/auth";
import "./globals.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner";
import { FaTimes } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const session = await auth();

  return (
    // <SessionProvider session={session}>
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster
          // closeButton
          toastOptions={{
            unstyled: true,
            classNames: {
              error:
                "bg-red-500 text-white px-4 py-3 rounded relative flex items-center shadow-md",
              success:
                "bg-green-500 text-white px-4 py-3 rounded relative flex items-center shadow-md",
              warning:
                "bg-yellow-500 text-white px-4 py-3 rounded relative flex items-center shadow-md",
              info: "bg-blue-500 text-white px-4 py-3 rounded relative flex items-center shadow-md",
            },
          }}
        />
      </body>
    </html>
    // </SessionProvider>
  );
}
